### ISSUE TITLE
Add docs on use with Moodle

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/ltiauthenticator#1]
Moodle supports being an LTI consumer (https://docs.moodle.org/34/en/External_tool). We should test this with Moodle to make sure it works, and add docs on how to use it with Moodle!

**Comment by fishfree** [comment]
I need the tutorial, too.

**Comment by manubraux** [comment]
Hello,
I have some trouble with Moodle testing.
Everything is Ok, but the oauth_signature is incorrect. I've checked and I think It is because I am using SSL Proxy.
The "launch_url" in the "base_string" construction containt : "http://mysite/hub/lti/launch" and not "httpS://mysite/hub/lti/launch".
Both Moodle and jupyterhub are using the SSL Proxy.
I'm python newbie, so could'd you please tell me where you get the value for  the "launch_url".
And then, I will  focus on Moodle, or on your plugin.
Thanks

**Comment by manubraux** [comment]
Hello.
I have found the problem. It was neiter a Moodle problem or ltiauthentificator. But with Nginx Reverse proxy configuration.
I have add the   "X-Forwarded-Proto" in the header
  proxy_set_header X-Forwarded-Proto $scheme;

**Comment by psychemedia** [comment]
@manubraux do you have a set of steps to follow / tutorial for setting up this authenticator against Moodle?

**Comment by consideRatio** [comment]
Closed by #20
