### ISSUE TITLE
setup.py missing in ltiauthenticator1.6.1

### ISSUE THREAD

**Issue by bpfrd** [jupyterhub/ltiauthenticator#183]
Hi,

I was wondering how I can install ltiauthenticator 1.6.1 from source.
I downloaded the code and wanted to install using `pip install -e .` after modifying a file but the `setup.py` is missing.
The modification i did was adding lti1.3 to the __init__ so that we can import it. currently it's not possible to import LTI13Authenticator.

best

**Comment by martinclaus** [comment]
There is no need for a `setup.py` for an editable install, if pip is of recent enough version since both, pip and hatchling, support [PEP 660](https://peps.python.org/pep-0660).

However, somehow the build process got broken which is probably the source of the problem. Once, #185 got merged, the main branch should be installable via `pip install -e .` again.

**Comment by martinclaus** [comment]
Fixed when #184 is fixed.
