### ISSUE TITLE
The token is not yet valid (iat) - lti1.3

### ISSUE THREAD

**Issue by bpfrd** [jupyterhub/ltiauthenticator#197]
Hello,

It seems that the `id_token` is not valid from now and there is a couple of seconds delay in my case which causes  `the token is not valid (iat)`. I described the issue here https://discourse.jupyter.org/t/the-token-is-not-yet-valid-iat/26342/3
I would like to know how this happens and how I can resolve it.  

best,

**Comment by martinclaus** [comment]
The reason for the problem is an offset in the system clocks of the two systems, the LTI platform and the hub. This may be caused by time zone settings or drift. Best is to use the same ntp server for both systems and to make sure that they regularly synchronise.

The validation of the token is delegated to the [pyjwt library](https://pyjwt.readthedocs.io/en/latest/index.html) which supports the specification of a [leeway margin](https://pyjwt.readthedocs.io/en/latest/usage.html#expiration-time-claim-exp) to account for synchronisation or clock drift issues.

You an configure the value of the leeway time in the [LTI13LaunchValidator](https://github.com/jupyterhub/ltiauthenticator/blob/b9513e98b38540050d2aa7a78de40185a034eed4/ltiauthenticator/lti13/validator.py#L34) class. It is a positive Integer value that gives the number of seconds that is allowed as a miss match. You can find an example [here](https://github.com/jupyterhub/ltiauthenticator/blob/main/examples/jupyterhub_config_lti13.py#L47).

I hope that helps 🤞🏻
