### ISSUE TITLE
Returning "result" from a Jupyter instance (more of a question than an issue)

### ISSUE THREAD

**Issue by willend** [jupyterhub/ltiauthenticator#28]
Hi there,

We are using your code to authenticate Jupyter sessions from a Moodle, which seems to work flawlessly for our initial purposes.

Later, we would in fact like to use LTI to communicate back a "result" from Jupyter (e.g. a number resulting from the execution of a cell) that would enter the Moodle grading system. 

Does any of the developers have hints in the direction of achieving this sort of functionality - or is that thought completely out of scope here?

Best
Peter

**Comment by willend** [comment]
@consideRatio or @samhinshaw you seem the latest 'active' developers here. Do you have any opinion on this issue?

(And is anyone in fact ever looking at tickets here? Or should I ask elsewhere? :-) )

Best
Peter

**Comment by consideRatio** [comment]
It is probably code that need to reside on the singleuser server rather than in the authenticator/jupyterhub end - im not sure though, hmmm a jupyterhub service perhaps?

I'm not sure, thats for sure! I would recommend asking this on discourse.jupyter.org for a broader audience. I dont know what lti or moodle is actuallty, I've mainly made sure this repo is somewhat up to date with CI/CD matters that are common for many jupyterhub related git repositories.

**Comment by ptcane** [comment]
@willend agree this would be fantastic. Not sure if you had seen there is / were talking about using this feature explicitly in [LTI v2](https://www.imsglobal.org/spec/lti-ags/v2p0/) (which I believe Moodle [now supports](https://docs.moodle.org/dev/LTI_2_support))

so, @consideRatio / @willend it would seem that's the route to implement this.. not something i could help with unfortunately but certainly a +1 for the feature request :)

**Comment by willend** [comment]
Hi both, thanks for the feedback. 

Do you have any tickets, commits, docs etc. pointing in the direction of what would be needed to move the code to LTI v2? 

(Then I or a colleague may start attempting a hack in that direction ;-) )

**Comment by ptcane** [comment]
@willend not beyond [the docs](https://www.imsglobal.org/spec/lti-ags/v2p0/#result-service)
you may find [nbgrader](https://github.com/jupyter/nbgrader) of interest. A couple of mentions of LTI in the issues but no implementation.
[Illumidesk](https://www.illumidesk.com/) is a commercial product which may also be of interest.

**Comment by claudevervoort** [comment]
Hi! Just a quick note that LTI v2 since I saw it mentioned here, it is a standard deprecated by IMS Global. The go to standards now is now LTI 1.3 which is based on OpenId Connect and OAuth 2.0. The ease of deployment it provides in Moodle will hopefully be replaced by https://tracker.moodle.org/browse/MDL-67301 in a subsequent release of Moodle. Moodle supports LTI 1.3 though I think since release 3.7.

**Comment by ptcane** [comment]
Thanks @claudevervoort

**Comment by consideRatio** [comment]
Thanks for the discussion everyone!

I'll close this issue at this point and ask that you help manage issues in this repo by re-opening a new issue focused on what remains relevant if there is a concrete action to take still.
