### ISSUE TITLE
Error 405 even after wel logged in

### ISSUE THREAD

**Issue by xandre31** [jupyterhub/ltiauthenticator#47]
Hi,

I just implemented my jupyterhub server with a LTI authenticator from a Moodle course.
I'm allowed to log in jupyerhub service but the jupyterhub interface is not showing in the Moodle course.
Here are the logs of my attempt : 

I 2021-05-31 11:50:41.667 JupyterHub base:663] User logged in: toto
[I 2021-05-31 11:50:41.668 JupyterHub log:174] 302 POST /hub/lti/launch -> /hub/home (@127.0.0.1) 13.06ms
[I 2021-05-31 11:50:41.700 JupyterHub log:174] 302 GET /hub/home -> /hub/login?next=%2Fhub%2Fhome (@127.0.0.1) 1.04ms
[I 2021-05-31 11:50:41.741 JupyterHub log:174] 302 GET /hub/login?next=%2Fhub%2Fhome -> /hub/lti/launch?next=%2Fhub%2Fhome (@127.0.0.1) 1.18ms
**[W 2021-05-31 11:50:41.776 JupyterHub log:174] 405 GET /hub/lti/launch?next=%2Fhub%2Fhome (@127.0.0.1) 2.04ms**
**[W 2021-05-31 11:50:41.889 JupyterHub log:174] 403 POST /hub/security/csp-report (@127.0.0.1) 1.99ms**

Why do I still get a 405 error code as I'm logged in as written in the first log ?

Thanks for your kind help !
Regards,

**Comment by jgwerner** [comment]
Hi @xandre31! Thanks for raising this issue. To better help you perhaps we can reproduce the error on our end. Could you confirm the following information?

- JuoyterHub version
- Operating system where the hub is running
- LTI Authenticator version: there have been some merges recently but we haven't cut a new release with these changes. If you are installing the package from source could you confirm the hash commit for the version?
- Browser version
- A copy of your JuoyterHub config

The last item in your stack trace looks like a [CSP error](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) so it's very likely that this issue isn't a bug but could be due to a configuration issue when using the JupyterHub when being accessed within an iFrame, which from what I understand is Moodle"s default. [This post has some information](https://stackoverflow.com/questions/60257156/not-able-to-embed-jupyterlab-running-on-jupyterhub-into-an-iframe) on how to configure your settings.

[I would also recommend searching in JupyterHub's community](https://discourse.jupyter.org/c/jupyterhub/10) site for configuration tips.

**Comment by xandre31** [comment]
Hi @jgwerner , thank you so much for your quick return.

I agree with you, it must be a parameter/configuration issue, but I'm not finding where and how to fix it.

- JupyterHub version : 
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py37_0    conda-forge
jupyterhub                1.0.0                    py37_0    conda-forge
jupyterhub-ltiauthenticator 1.0.0                    pypi_0    pypi
jupyterlab                1.1.1                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge

- Operating system where the hub is running : CentOS 7.9
- LTI Authenticator version:  Package has been installed form pypi, following given instructions
- Browser version : Google Chrome
- A copy of your JupyterHub config : for security reasons I removed key and secret from my config file :

import sys

# Set the log level by value or name.
c.JupyterHub.log_level = 'DEBUG'

#  This is the address on which the proxy will bind. Sets protocol, ip, base_url
c.JupyterHub.bind_url = 'http://127.0.0.1:8000'


## File in which to store the cookie secret.
c.JupyterHub.cookie_secret_file = '/opt/jupyterhub/jupyterhub_cookie_secret'

c.Spawner.default_url = '/lab'

c.Authenticator.admin_users = {'a_andre'}

c.LocalAuthenticator.create_system_users = True
c.LocalAuthenticator.add_user_cmd = ['adduser', '-m', '-gusers']

c.JupyterHub.shutdown_on_logout = True

import os
for var in os.environ:
    c.Spawner.env_keep.append(var)

c.JupyterHub.services = [
        {
                'name': 'cull-idle',
                'admin': True,
                'command': [sys.executable, '/opt/jupyterhub/cull_idle_servers.py', '--timeout=3600'],
        }
]

from subprocess import check_call
def my_hook(spawner):
    username = spawner.user.name
    check_call(['/root/scripts/users/check_homedir.sh', username])
c.Spawner.pre_spawn_hook = my_hook

# Authentication from Moodle platform (LMS)
c.JupyterHub.authenticator_class = 'ltiauthenticator.LTIAuthenticator'
c.LTIAuthenticator.consumers = {
    "XXXX": "YYYY"
}

LTI Authentication seems to works as I have the following log : I 2021-05-31 11:50:41.667 JupyterHub base:663] User logged in: toto

**Comment by xandre31** [comment]
I've changed Moodle course configuration to force Jupyterhub to be opened in a new window and that fixes my issue.

Thanks again for you analisys and help !

**Comment by jgwerner** [comment]
@xandre31 thanks for confirming! This is a pretty common issue due to the new `SameSite` security settings. Sometimes these settings will inhibit setting the cookie in the browser so you would have to change _both_ the JupyterHub and the Jupyter Notebook / JupyterLab configs (essentially upstream Tornado Web configs) to support these settings. [This Issue thread](https://github.com/jupyterhub/jupyterhub/issues/3117) has some more context and some external links to help you define these configuration settings.
